version: '3'

services:
  chromedriver:
    image: quay.io/imdocker1/docker-chromedriver
    privileged: true
    restart: always
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=''
    # ports:
    #   - '4444:4444'
    depends_on:
      - selenium-side-runner

  selenium-side-runner:
    image: quay.io/imdocker1/docker-selenium-side-runner
    # build:
    #   context: .
    volumes:
      - './sides:/sides:z'
      - './out:/out:z'
